apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
   
  
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: payment
#   namespace: roboshop
# type: Opaque
# data:
#   AMQP_USER: cm9ib3Nob3AK
#   AMQP_PASS: cm9ib3Nob3AxMjMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: payment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: payment
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: payment
        tier: backend
    spec:
      containers:
        - name: payment
          image: kdrajr/payment:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: payment
            # - secretRef:
            #     name: payment
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: payment
    tier: backend
spec:
  selector:
    project: roboshop
    environment: dev
    component: payment
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080