apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: cart
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: cart
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: cart
        tier: backend
    spec:
      containers:
        - name: cart
          image: kdrajr/cart:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cart
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: cart
    tier: backend
spec:
  selector:
    project: roboshop
    environment: dev
    component: cart
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
