apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: shipping
        tier: backend
    spec:
      containers:
        - name: shipping
          image: kdrajr/shipping:v1
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: shipping
    tier: backend
spec:
  selector:
    project: roboshop
    environment: dev
    component: shipping
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
