apiVersion: v1
kind: Secret
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: db
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3AK
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjMK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: rabbitmq
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: rabbitmq
        tier: db
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13
          imagePullPolicy: Always
          envFrom:
            - secretRef: 
                name: rabbitmq
          ports:
            - containerPort: 5672
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: db
spec:
  selector:
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
