apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: kdrajr/mongodb:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    project: roboshop
    environment: dev
    component: mongodb
    tier: db
spec:
  selector:
    project: roboshop
    environment: dev
    component: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
