apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
    tier: db
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: kdrajr/mysql:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          # readinessProbe:
          #   tcpSocket:
          #     port: 3306
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 3306
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
    tier: db
spec: 
  selector:
    project: roboshop
    environment: dev
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
