apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: redis
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: redis
      tier: db
  template:
    metadata:
      name: redis
      labels:
        project: roboshop
        environment: dev
        component: redis
        tier: db
    spec:
      containers:
        - name: redis
          image: redis:7.0
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: redis
    tier: db
spec:
  selector:
    project: roboshop
    environment: dev
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      